### ISSUE TITLE
Issue with 2.3 realse

### ISSUE THREAD

**Issue by David999989** [TortoiseDev/GogoBatcherDio#4]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 123, in run
    completed_proc = subprocess.run(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 1948, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 14] Bad address: '/data/data/com.termux/files/usr/lib/python3.11/site-packages/selenium/webdriver/common/linux/selenium-manager'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 38, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 90, in driver_location
    output = self.run(args)
             ^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 129, in run
    raise WebDriverException(f"Unsuccessful command executed: {command}") from err
selenium.common.exceptions.WebDriverException: Message: Unsuccessful command executed: /data/data/com.termux/files/usr/lib/python3.11/site-packages/selenium/webdriver/common/linux/selenium-manager --browser chrome --output json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/storage/emulated/0/Download/GogoBatcherDio-2.3/app.py", line 285, in <module>
    start()
  File "/storage/emulated/0/Download/GogoBatcherDio-2.3/app.py", line 146, in start
    link : str = makeLink(name)
                 ^^^^^^^^^^^^^^
  File "/storage/emulated/0/Download/GogoBatcherDio-2.3/app.py", line 119, in makeLink
    driver = webdriver.Chrome(options=chromeOptions)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 51, in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 41, in get_path
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

I'm pretty sure this is because I'm using an Android device. But it would be nice if you can fix it.

**Comment by TortoiseShell04** [comment]
are you running on termux?

**Comment by David999989** [comment]
> are you running on termux?

Yes with python 3.11

**Comment by TortoiseShell04** [comment]
Alright, replace line 10 with 
```from selenium.webdriver.firefox.options import Options``` 
and line 119 with 
```driver = webdriver.Firefox(options=chromeOptions)```
and run ```pkg install firefox``` on termux

**Comment by David999989** [comment]
> 
It gives this error
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 123, in run
    completed_proc = subprocess.run(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 1948, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/data/data/com.termux/files/usr/lib/python3.11/site-packages/selenium/webdriver/common/linux/selenium-manager'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 38, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 90, in driver_location
    output = self.run(args)
             ^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 129, in run
    raise WebDriverException(f"Unsuccessful command executed: {command}") from err
selenium.common.exceptions.WebDriverException: Message: Unsuccessful command executed: /data/data/com.termux/files/usr/lib/python3.11/site-packages/selenium/webdriver/common/linux/selenium-manager --browser firefox --output json


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/storage/emulated/0/Download/GogoBatcherDio-2.3/app2.py", line 285, in <module>
    start()
  File "/storage/emulated/0/Download/GogoBatcherDio-2.3/app2.py", line 146, in start
    link : str = makeLink(name)
                 ^^^^^^^^^^^^^^
  File "/storage/emulated/0/Download/GogoBatcherDio-2.3/app2.py", line 119, in makeLink
    driver = webdriver.Firefox(options=chromeOptions)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/selenium/webdriver/firefox/webdriver.py", line 59, in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 41, in get_path
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for firefox using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

**Comment by David999989** [comment]
> Alright, replace line 10 with 
> ```from selenium.webdriver.firefox.options import Options``` 
> and line 119 with 
> ```driver = webdriver.Firefox(options=chromeOptions)```
> and run ```pkg install firefox``` on termux

If it's not possible for u to fix right now. It's ok I'm still using the older version and manually download like the 2 which the script didn't download which is fine it already has saved a bunch of time for me. And thanks again u don't know how much it does help.
